(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



If[($OperatingSystem=="Windows"),<< "C:\\Documents and Settings\\ocroissant\\My Documents\\BS.m",
<< "/Users/oliviercroissant/Documents/Math/BS.m"]


<<"PlotLegends`"


Off[FindRoot::"precw"]


zz[K_,F0_,\[Epsilon]_,\[Beta]_]:=K \[Epsilon]^(-\[Beta]/2) Hypergeometric2F1[1/2,\[Beta]/2,3/2,-(K^2/\[Epsilon])]-F0 \[Epsilon]^(-\[Beta]/2) Hypergeometric2F1[1/2,\[Beta]/2,3/2,-(F0^2/\[Epsilon])]


zz0[K_,F0_,\[Beta]_]:=F0^(1-\[Beta])/(-1+\[Beta])-K^(1-\[Beta])/(-1+\[Beta])


LocalVolCall[CC_,CCDev1_,CCDev2_,CCInvInteg_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav},
fav=(F+K)/2;
w=1/Sqrt[2 T] (CCInvInteg[K]-CCInvInteg[F]);
H1=2(E^-w^2+Sqrt[\[Pi] w^2](NormDis[Sqrt[2]Abs[w]]-1));
H2=2/3 (E^-w^2 (1-2w^2)-2(Abs[w])^3 Sqrt[\[Pi]](NormDis[Sqrt[2]Abs[w]]-1));
Q=CC[fav]^2/4 ((CCDev2[fav]/CC[fav])-1/2 (CCDev1[fav]/CC[fav])^2);
Max[F-K,0]+Sqrt[CC[K] CC[F] T]/(2Sqrt[2\[Pi]]) (H1+T H2 Q)
]


SABRCC[F_,alpha_,beta_,epsilon_]:=alpha (F^2+epsilon)^(beta/2)


SABRCCDev1[F_,alpha_,beta_,epsilon_]:=alpha beta F (epsilon+F^2)^(-1+beta/2)


SABRCCDev2[F_,alpha_,beta_,epsilon_]:=alpha beta (epsilon+F^2)^(-2+beta/2) (epsilon+(-1+beta) F^2)


SABRCCInvInteg[F_,alpha_,\[Beta]_,\[Epsilon]_]:=alpha F (1+F^2/\[Epsilon])^(\[Beta]/2) (F^2+\[Epsilon])^(-\[Beta]/2) Hypergeometric2F1[1/2,\[Beta]/2,3/2,-(F^2/\[Epsilon])]


SABRCall[F_,K_,vol_,T_,beta_,epsilon_]:=
Module[{},
LocalVolCall[(SABRCC[#,vol,beta,epsilon])&,(SABRCCDev1[#,vol,beta,epsilon])&,(SABRCCDev2[#,vol,beta,epsilon])&,(SABRCCInvInteg[#,vol,beta,epsilon])&,F,K,T]
]


\[CapitalPhi]SAbr[T_,x_,M_]:=Re[1/(2 Sqrt[-M]) E^(-Sqrt[2] Sqrt[-M] x) Sqrt[\[Pi]] (1-E^(2 Sqrt[2] Sqrt[-M] x)+E^(2 Sqrt[2] Sqrt[-M] x) Erf[x/(Sqrt[2] Sqrt[T])+Sqrt[-M] Sqrt[T]]-Erf[x/(Sqrt[2] Sqrt[T])-Sqrt[-M] Sqrt[T]])]


SABROptionAnalyticOption[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{z,zp,x,b1,\[Theta],\[FinalSigma],\[Kappa],result,\[Sigma],a,b,sig,sigN,fav2,\[Gamma]1,\[Gamma]2,\[Xi],call,fav},
fav=(f+K)/2;
If[\[Beta]!=1, z=(f^(1-\[Beta])-K^(1-\[Beta]))/(\[Alpha] (1-\[Beta])),z=Log[f]/\[Alpha]-Log[K]/\[Alpha]];
If[\[Beta]!=1, \[Xi]=\[Nu] (f^(1-\[Beta])-K^(1-\[Beta]))/(\[Alpha] (1-\[Beta])), \[Xi]=\[Nu] (Log[f]/\[Alpha]-Log[K]/\[Alpha])];
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
b1=\[Beta] fav^(\[Beta]-1);
If[z==0,\[Theta]=0,
\[Theta]=1/4 \[Alpha] b1 \[Nu] \[Rho] z^2+Log[(\[Alpha] (f K)^(\[Beta]/2) z)/(f-K)]+Log[(x (1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2)^(1/4))/z]];
\[Kappa]=1/8 ((\[Alpha]^2 (-2+\[Beta]) \[Beta] K^(2 \[Beta]))/K^2+(6 \[Alpha] \[Beta] K^\[Beta] \[Nu] \[Rho])/K+\[Nu]^2 (2-3 \[Rho]^2));
If[z==0,call=(K^\[Beta] \[Alpha])/(2 Sqrt[2 \[Pi]]) \[CapitalPhi]SAbr[T,Abs[x],\[Kappa]],
call=N[Max[f-K,0]+(f-K)/(2Sqrt[2\[Pi]]) E^\[Theta]/x \[CapitalPhi]SAbr[T,Abs[x],\[Kappa]]]];
call];


SABROptionAnalyticVol[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{call},
call=SABROptionAnalyticOption[f,\[Alpha],\[Beta],\[Rho],\[Nu],K,T];
ImpVolBS[f,K,T,1,call]];


SABROptionAnalyticNVol[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{call},
call=SABROptionAnalyticOption[f,\[Alpha],\[Beta],\[Rho],\[Nu],K,T];
NormalImplicitVol[f,K,T,call]];


 SABRHaganVol[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{z,x,Effetmat},z=(f^(1-\[Beta])-K^(1-\[Beta]))/(\[Alpha] (1-\[Beta]));
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
Effetmat=(1+(1/24 \[Alpha]^2 (1-\[Beta])^2 (f K)^(-1+\[Beta])+1/4 \[Alpha] \[Beta] (f K)^(1/2 (-1+\[Beta])) \[Nu] \[Rho]+1/24 \[Nu]^2 (2-3 \[Rho]^2)) T)/(1+1/24 (1-\[Beta])^2 Log[f/K]^2+((1-\[Beta])^4 Log[f/K]^4)/1920);
If[z==0,K^(-1+\[Beta]) \[Alpha] Effetmat,
\[Alpha]/(f K)^((1-\[Beta])/2 ) z/x  Effetmat  ]]


 SABRHaganOption[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{vol},
vol=  SABRHaganVol[f,\[Alpha],\[Beta],\[Rho],\[Nu],K,T];
BS[f,K,T,vol ]]


NonCentralChi[\[Nu]_,\[Lambda]_,z_]:=CDF[NoncentralChiSquareDistribution[\[Nu],\[Lambda]],z]


CEVCall[F_,K_,vol_,r_,T_,beta_]:=Module[{Sp,Kp,k=If[r==0,1/(2vol^2 (1-beta)^2 T),r/(vol^2 (1-beta)(E^(r T (2-2beta))-1))]},
Sp=F^(2-2beta) E^(-r T (2-2beta)) k;
Kp=K^(2-2beta) k;
F (1-NonCentralChi[2+2/(2-2beta),2Sp,2Kp])-E^(-r T) K NonCentralChi[2/(2-2beta),2Kp,2Sp]]


CEVCall[F_,K_,vol_,T_,beta_]:=Module[{Sp,Kp,k=1/(2vol^2 (1-beta)^2 T)},
Sp=F^(2-2beta) k;
Kp=K^(2-2beta) k;
F (1-NonCentralChi[2+2/(2-2beta),2Sp,2Kp])-K NonCentralChi[2/(2-2beta),2Kp,2Sp]]


CEVCall1[F_,K_,vol_,T_,beta_]:=Module[{Sp,Kp,k=1/(2vol^2 (1-beta)^2 T),Y},
Sp=F^(2-2beta) k;
Kp=K^(2-2beta) k;Y=1/(2-2beta);
F -(\!\(
\*SubsuperscriptBox[\(\[Integral]\), \(0\), \(1\)]\(
SuperscriptBox[\(z\), \(Y\)] \((
\*SuperscriptBox[\(E\), \(-\((Kp\ z + Sp)\)\)]\ F 
\*SuperscriptBox[\((Kp\ )\), \(1 + Y\)]\ Hypergeometric0F1Regularized[1 + Y, Kp\ z\ Sp] + 
\*SuperscriptBox[\(E\), \(-\((Sp\ z + Kp)\)\)]\ K\ 
\*FractionBox[
SuperscriptBox[\((Sp\ )\), \(Y\)], \(z\)]\ Hypergeometric0F1Regularized[Y, Sp\ z\ Kp])\) \[DifferentialD]z\)\))]


CEVCallDK[F_,K_,vol_,T_,beta_]:=Module[{Sp,Kp,k=1/(2vol^2 (1-beta)^2 T),Y},
Sp=F^(2-2beta) k;
Kp=K^(2-2beta) k;Y=1/(2-2beta);
N[(\!\(
\*SubsuperscriptBox[\(\[Integral]\), \(0\), \(1\)]\(
SuperscriptBox[\(z\), \(Y\)] \((
FractionBox[\(1\), \(z\)] 
\*SuperscriptBox[\(E\), \(\(-\((Kp + \ Sp)\)\)\ \ \((1 + z)\)\)]\ \ \((
\*SuperscriptBox[\(E\), \(Sp + Kp\ z\)]\ \((2\ \((\(-1\) + beta)\)\ k\ 
\*SuperscriptBox[\(K\), \(2 - 2  beta\)] + 1)\)\ 
\*SuperscriptBox[\(Sp\), \(Y\)]\ Hypergeometric0F1Regularized[Y, Kp\ Sp\ z] - 2\ \((\(-1\) + beta)\)\ k\ \ z\ \((\((
\*SuperscriptBox[\(E\), \(Sp + Kp\ \ z\)]\ 
\*SuperscriptBox[\(K\), \(2 - 2\ beta\)]\ 
\*SuperscriptBox[\(Sp\), \(1 + Y\)] + 
\*SuperscriptBox[\(E\), \(Kp + Sp\ z\)]\ F\ \ \ 
\*SuperscriptBox[\(k\), \(Y\)]\ \((
\*SuperscriptBox[\(K\), \(2 - 2\ beta\)]\ \((1 + Y)\) - k\ 
\*SuperscriptBox[\(K\), \(4 - 4  beta\)]\ z)\))\)\ Hypergeometric0F1Regularized[1 + Y, Kp\ \ Sp\ z] + 
\*SuperscriptBox[\(E\), \(Kp + Sp\ z\)]\ F\ k\ 
\*SuperscriptBox[\(K\), \(4 - 4  beta\)]\ 
\*SuperscriptBox[\(k\), \(Y\)]\ Sp\ z\ Hypergeometric0F1Regularized[2 + Y, Kp\ \ Sp\ z])\))\))\) \[DifferentialD]z\)\))]]


CEVBSVol[F_,K_,vol_,drift_,T_,beta_]:=ImpVolBS[F,K,T,CEVCall[F,K,vol,drift,T,beta]]


CEVCallDK0[F_,vol_,T_,beta_]:=Module[{Sp,Kp,k=1/(2vol^2 (1-beta)^2 T),Y},
Sp=F^(2-2beta) k;
Y=1/(2-2beta);
\!\(
\*SubsuperscriptBox[\(\[Integral]\), \(0\), \(1\)]\(
SuperscriptBox[\(z\), \(Y - 1\)] 
\*SuperscriptBox[\(E\), \(\(-\ Sp\)\ \ z\)]\ \ 
\*SuperscriptBox[\(Sp\), \(Y\)]\ Hypergeometric0F1Regularized[Y, 0] \[DifferentialD]z\)\)]


CEVDensity[F_,K_,vol_,T_,beta_]:=Module[{shift=0.0001},-(CEVCallDK[F,K+shift,vol,T,beta]-CEVCallDK[F,K-shift,vol,T,beta])/(2shift)]


CEVDistribution[F_,K_,vol_,drift_,T_,beta_]:=Module[{shift=0.0001},(-CEVCall[F,K+shift,vol,drift,T,beta]+CEVCall[F,K-shift,vol,drift,T,beta])/(2shift)]


CEVDensity1[F_,K_,vol_,r_,T_,beta_]:=Module[{Sp,Kp,k=If[r==0,1/(2vol^2 (1-beta)^2 T),r/(vol^2 (1-beta)(E^(r T (2-2beta))-1))]},
Sp=F^(2-2beta) E^(-r T (2-2beta)) k;
Kp=K^(2-2beta) k;
(2-2beta) k^(1/(2-2beta)) (Sp Kp^(1-4beta))^(1/(4-4beta)) E^(-Sp-Kp) BesselI[1/(2-2beta),(2Sqrt[Sp Kp])]
]


LocalVolCall[CC_,CCDev1_,CCDev2_,CCInvInteg_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav},
fav=(F+K)/2;
w=1/Sqrt[2 T] (CCInvInteg[K]-CCInvInteg[F]);
H1=2(E^-w^2+Sqrt[\[Pi] w^2](NormDis[Sqrt[2]Abs[w]-1]));
H2=2/3 (E^-w^2 (1-2w^2)-2(Abs[w])^3 Sqrt[\[Pi]](NormDis[Sqrt[2]Abs[w]]-1));
Q=CC[fav]^2/4 ((CCDev2[fav]/CC[fav])-1/2 (CCDev1[fav]/CC[fav])^2);
Max[F-K,0]+Sqrt[CC[K] CC[F] T]/(2Sqrt[2\[Pi]]) (H1+T H2 Q)
]


LocalVolBSVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav,b1,b2,b3},
fav=(F+K)/2;
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
Log[K/F]/(CCInvInteg[K]-CCInvInteg[F]) (1+T (b3))
]


SABRCC[F_,alpha_,beta_]:=alpha F^beta


SABRCCDev1[F_,alpha_,beta_]:=alpha beta F^(beta-1)


SABRCCDev2[F_,alpha_,beta_]:=alpha  beta (beta-1) F^(beta-2)


SABRCCInvInteg[F_,alpha_,beta_]:=F^(1-beta)/((1-beta)alpha)


SABRCall[F_,K_,vol_,T_,beta_]:=
Module[{},
LocalVolCall[(SABRCC[#,vol,beta])&,(SABRCCDev1[#,vol,beta])&,(SABRCCDev2[#,vol,beta])&,(SABRCCInvInteg[#,vol,beta])&,F,K,T]
]


CEVVolApprox3[F_,K_,vol_,T_,beta_]:=
Module[{},
LocalVolBSVol[(SABRCC[#,vol,beta])&,(SABRCCDev1[#,vol,beta])&,(SABRCCDev2[#,vol,beta])&,(SABRCCInvInteg[#,vol,beta])&,0,0,F,K,T]
]


CEVVolApprox[F_,K_,vol_,T_,beta_]:=ImpVolBS[F,K,T,SABRCall[F,K,vol,T,beta]]


CEVVolApprox2[F_,K_,vol_,T_,beta_]:=Module[{fav=(F+K)/2},(vol (1-beta)Log[K/F])/(K^(1-beta)-F^(1-beta)) (1+(beta-1)^2/24 vol^2 T fav^(2beta-2))]


ImpVolCEV[F_,K_,T_,beta_,discount_,opt_]:=Module[{r=Log[discount]/T,ss,vol=ImpVolBS[F,K,T,opt]},
ss=FindRoot[CEVVolApprox2[F, K, u, T, beta]==vol,{u,0.1,0.003,7.},AccuracyGoal->8,WorkingPrecision->30,MaxIterations->200];ss[[1,2]]]


 SABRHaganVol[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{z,x,Effetmat},z=(f^(1-\[Beta])-K^(1-\[Beta]))/(\[Alpha] (1-\[Beta]));
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
Effetmat=(1+(1/24 \[Alpha]^2 (1-\[Beta])^2 (f K)^(-1+\[Beta])+1/4 \[Alpha] \[Beta] (f K)^(1/2 (-1+\[Beta])) \[Nu] \[Rho]+1/24 \[Nu]^2 (2-3 \[Rho]^2)) T)/(1+1/24 (1-\[Beta])^2 Log[f/K]^2+((1-\[Beta])^4 Log[f/K]^4)/1920);
If[z==0,K^(-1+\[Beta]) \[Alpha] Effetmat,
\[Alpha]/(f K)^((1-\[Beta])/2 ) z/x  Effetmat  ]]


zzp[F_,K_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=(F^(1-\[Beta]2)-K^(1-\[Beta]2)) /(1-\[Beta]2)+\[Lambda]^(\[Beta]1-1) (-Gamma[1-\[Beta]1,F \[Lambda]]+Gamma[1-\[Beta]1,K \[Lambda]])+\[Lambda]^(\[Beta]2-1) (Gamma[1-\[Beta]2,F \[Lambda]]-Gamma[1-\[Beta]2,K \[Lambda]])


zz0[K_,F0_,\[Beta]_]:=F0^(1-\[Beta])/(-1+\[Beta])-K^(1-\[Beta])/(-1+\[Beta])


StochVolBSVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav,b1,b2,b3,x,z},
fav=Sqrt[F K];
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);
b2=1/4 CCDev1[fav] \[Nu] \[Rho];
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
z=(CCInvInteg[F]-CCInvInteg[K]);
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
Log[F/K]/x (1+T (b1+b2+b3))
]


StochVolBSVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_,fav_]:=Module[{w,H1,H2,Q,b1,b2,b3,x,z},
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);
b2=1/4 CCDev1[fav] \[Nu] \[Rho];
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
z=(CCInvInteg[F]-CCInvInteg[K]);
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[F-K]<10^-7,Abs[CC[F]] /F (1+T (b1+b2+b3)),Abs[Log[F/K]/x] (1+T (b1+b2+b3))]
]


StochVolNormVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav,b1,b2,b3,x,z},
fav=(F+K)/2;
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);
b2=1/4 CCDev1[fav] \[Nu] \[Rho];
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
z=(CCInvInteg[F]-CCInvInteg[K]);
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
Abs[(K-F)/x](1+T (b1+b2+b3))
]


StochVolNormVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_,fav_]:=Module[{w,H1,H2,Q,b1,b2,b3,x,z},
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);b2=1/4 CCDev1[fav] \[Nu] \[Rho];b3=1/24  (2 CCDev2[fav]CC[fav]-(CCDev1[fav])^2+1);
z=CCInvInteg[F]-CCInvInteg[K];
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[F-K]<10^-7,Abs[CC[F]] (1+T (b1+b2+b3)),Abs[(K-F)/x] (1+T (b1+b2+b3))]]


SABRCC[F_,alpha_,beta_]:=alpha F^beta


SABRCCDev1[F_,alpha_,beta_]:=alpha beta F^(beta-1)


SABRCCDev2[F_,alpha_,beta_]:=alpha  beta (beta-1) F^(beta-2)


SABRCCInvInteg[F_,alpha_,beta_]:=F^(1-beta)/((1-beta)alpha)


SABRCallBSVolApprox[F_,K_,vol_,T_,beta_,\[Rho]_,\[Nu]_]:=
Module[{},
StochVolBSVol[(SABRCC[#,vol,beta])&,(SABRCCDev1[#,vol,beta])&,(SABRCCDev2[#,vol,beta])&,(SABRCCInvInteg[#,vol,beta])&,\[Rho],\[Nu],F,K,T,Sqrt[F K]]
]


SABRCallNormVol[F_,K_,alpha_,T_,beta_,\[Rho]_,\[Nu]_]:=
Module[{},
StochVolNormVol[(SABRCC[#,alpha,beta])&,(SABRCCDev1[#,alpha,beta])&,(SABRCCDev2[#,alpha,beta])&,(SABRCCInvInteg[#,alpha,beta])&,\[Rho],\[Nu],F,K,T,(F+K)/2]
]


PSABRCC[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=\[Alpha] ((1/(1+F^(\[Beta]1-\[Beta]2) (E^(\[Lambda] F)-1))) F^\[Beta]1+F^\[Beta]2 (1-1/(1+F^(\[Beta]1-\[Beta]2) (E^(\[Lambda] F)-1))))


PSABRCCDev1[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=(E^(F \[Lambda]) F^(-1+\[Beta]1+\[Beta]2) \[Alpha] (F^\[Beta]2 \[Beta]1+(-1+E^(F \[Lambda])) F^\[Beta]1 \[Beta]2-F^(1+\[Beta]1) \[Lambda]+F^(1+\[Beta]2) \[Lambda]))/((-1+E^(F \[Lambda])) F^\[Beta]1+F^\[Beta]2)^2


PSABRCCDev2[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=1/((-1+E^(F \[Lambda])) F^\[Beta]1+F^\[Beta]2)^3 E^(F \[Lambda]) F^(-2+\[Beta]1+\[Beta]2) \[Alpha] (F^(2 \[Beta]2) (-1+\[Beta]1) \[Beta]1+(-1+E^(F \[Lambda]))^2 F^(2 \[Beta]1) (-1+\[Beta]2) \[Beta]2-(-1+E^(F \[Lambda])) F^(\[Beta]1+\[Beta]2) (\[Beta]1+\[Beta]1^2+\[Beta]2-4 \[Beta]1 \[Beta]2+\[Beta]2^2)+2 F^(1+2 \[Beta]2) \[Beta]1 \[Lambda]-2 (-1+E^(F \[Lambda])) F^(1+2 \[Beta]1) \[Beta]2 \[Lambda]-2 F^(1+\[Beta]1+\[Beta]2) (\[Beta]1+E^(F \[Lambda]) \[Beta]1+\[Beta]2-2 E^(F \[Lambda]) \[Beta]2) \[Lambda]+(1+E^(F \[Lambda])) F^(2+2 \[Beta]1) \[Lambda]^2-(2+E^(F \[Lambda])) F^(2+\[Beta]1+\[Beta]2) \[Lambda]^2+F^(2+2 \[Beta]2) \[Lambda]^2)


PSABRCCInvInteg[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=1/\[Alpha] ((F^(1-\[Beta]2)-K^(1-\[Beta]2)) /(1-\[Beta]2)+\[Lambda]^(\[Beta]1-1) (-Gamma[1-\[Beta]1,F \[Lambda]]+Gamma[1-\[Beta]1,K \[Lambda]])+\[Lambda]^(\[Beta]2-1) (Gamma[1-\[Beta]2,F \[Lambda]]-Gamma[1-\[Beta]2,K \[Lambda]]))


PSABRCallBSVol[F_,K_,\[Alpha]_,T_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_]:=
Module[{fav=F},
StochVolBSVol[(PSABRCC[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev1[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev2[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCInvInteg[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,\[Rho],\[Nu],F,K,T,fav]
]


PSABRCallBSOption[F_,K_,\[Alpha]_,T_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_]:=BS[K,K,T,PSABRCallBSVol[F,K,\[Alpha],T,\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu]]]


PSABRCallBSDigitale[F_,K_,\[Alpha]_,T_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_]:=Module[{s1,s2,shift=0.00001},
s1=PSABRCallBSOption[F,K+shift,\[Alpha],T,\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu]];
s2=PSABRCallBSOption[F,K-shift,\[Alpha],T,\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu]];
(s2-s1)/(2shift)
]


PSABRCallNormVol[F_,K_,\[Alpha]_,T_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_]:=
Module[{fav=F},
StochVolNormVol[(PSABRCC[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev1[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev2[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCInvInteg[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,\[Rho],\[Nu],F,K,T,fav]
]


PSABRCallNormOption[F_,K_,\[Alpha]_,T_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_]:=NormalCall[F,PSABRCallNormVol[F,K,\[Alpha],T,\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu]],K,T]


PSABRCallNormDigitale[F_,K_,\[Alpha]_,T_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_]:=Module[{s1,s2,shift=0.00001},
s1=PSABRCallNormOption[F,K+shift,\[Alpha],T,\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu]];
s2=PSABRCallNormOption[F,K-shift,\[Alpha],T,\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu]];
(s2-s1)/(2shift)]



ESABRCC[F_,alpha_,beta_,\[Epsilon]_]:=alpha (\[Epsilon]+F)^beta


ESABRCCDev1[F_,alpha_,beta_,\[Epsilon]_]:=alpha beta (\[Epsilon]+F)^(beta-1)


ESABRCCDev2[F_,alpha_,beta_,\[Epsilon]_]:=alpha  beta (beta-1) (\[Epsilon]+F)^(beta-2)


ESABRCCInvInteg[F_,alpha_,\[Beta]_,\[Epsilon]_]:=(F \[Epsilon]^(-\[Beta]/2) Hypergeometric2F1[1/2,\[Beta]/2,3/2,-(F^2/\[Epsilon])])/alpha


ESABRCallBSVol[F_,K_,vol_,T_,beta_,\[Rho]_,\[Nu]_,\[Epsilon]_]:=
Module[{},
StochVolBSVol[(ESABRCC[#,vol,beta,\[Epsilon]])&,(ESABRCCDev1[#,vol,beta,\[Epsilon]])&,(ESABRCCDev2[#,vol,beta,\[Epsilon]])&,(ESABRCCInvInteg[#,vol,beta,\[Epsilon]])&,\[Rho],\[Nu],F,K,T]
]


ESABRCallNormVol[F_,K_,alpha_,T_,beta_,\[Rho]_,\[Nu]_,\[Epsilon]_]:=
Module[{},
StochVolNormVol[(ESABRCC[#,alpha,beta,\[Epsilon]])&,(ESABRCCDev1[#,alpha,beta,\[Epsilon]])&,(ESABRCCDev2[#,alpha,beta,\[Epsilon]])&,(ESABRCCInvInteg[#,alpha,beta,\[Epsilon]])&,\[Rho],\[Nu],F,K,T,F]
]


f[F_]:=F \[Epsilon]^(-\[Beta]/2) Hypergeometric2F1[1/2,\[Beta]/2,3/2,-(F^2/\[Epsilon])]


CC[F_,\[Beta]_,\[Epsilon]_]:=(F^2+\[Epsilon])^(\[Beta]/2)


f1[F_,\[Gamma]_,F0_]:=f[\[Gamma] Sinh[(F-F0)/\[Gamma]]+F0]-f[F0]


CC[F_,\[Beta]_,\[Epsilon]_,\[Gamma]_,F0_]:= Sech[(F-F0)/\[Gamma]] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2)


EZSABRCC[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=\[Alpha] Sech[(F-F0)/\[Gamma]] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2)


EZSABRCCDev1[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=\[Alpha] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2) ((\[Beta] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]]))/(\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))-(Sech[(F-F0)/\[Gamma]] Tanh[(F-F0)/\[Gamma]])/\[Gamma])


EZSABRCCDev2[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=\[Alpha] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2) (-(Sech[(F-F0)/\[Gamma]]^3/\[Gamma]^2)+((-2+\[Beta]) \[Beta] Cosh[(F-F0)/\[Gamma]] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2)/(\[Epsilon]^2 (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon])^2)+(\[Beta] Cosh[(F-F0)/\[Gamma]])/(\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))-(\[Beta] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]]) Tanh[(F-F0)/\[Gamma]])/(\[Gamma] \[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))+(Sech[(F-F0)/\[Gamma]] Tanh[(F-F0)/\[Gamma]]^2)/\[Gamma]^2)


EZSABRCCInvInteg[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=1/\[Alpha]  \[Epsilon]^(-\[Beta]/2) (Hypergeometric2F1[1/2,\[Beta]/2,3/2,-((F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon])] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]]))


EZSABRCallBSVol[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_]:=
Module[{fav=F},
StochVolBSVol[(EZSABRCC[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev1[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev2[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCInvInteg[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,\[Rho],\[Nu],F,K,T,fav]
]


EZSABRCallBSOption[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_]:=BS[K,K,T,EZSABRCallBSVol[F,K,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]]]


EZSABRCallBSDigitale[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_]:=Module[{s1,s2,shift=0.00001},
s1=EZSABRCallBSOption[F,K+shift,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]];
s2=EZSABRCallBSOption[F,K-shift,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]];
(s2-s1)/(2shift)
]


EZSABRCallNormVol[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_]:=
Module[{fav=F},
StochVolNormVol[(EZSABRCC[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev1[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev2[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCInvInteg[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,\[Rho],\[Nu],F,K,T,fav]
]


SABRHaganDigitale[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_]:=Module[{s1,s2,shift=0.00001},
s1=SABRHaganOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K+shift,T];
s2=SABRHaganOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)]



EZSABRCallNormOption[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_]:=NormalCall[F,EZSABRCallNormVol[F,K,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]],K,T]


EZSABRCallNormDigitale[F_,K_,\[Alpha]_,T_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_]:=Module[{s1,s2,shift=0.00001},
s1=EZSABRCallNormOption[F,K+shift,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]];
s2=EZSABRCallNormOption[F,K-shift,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]];
(s2-s1)/(2shift)]




