(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Gup[f,f]=1/2 a^2 C[f]^2;Gup[a,f]=1/2 a \[Rho] C[f] \[Sigma][a];Gup[f,a]=1/2 a \[Rho] C[f] \[Sigma][a];Gup[a,a]=\[Sigma][a]^2/2;


Gdown[f,f]=-(2/(a^2 (-1+\[Rho]^2) C[f]^2));Gdown[a,f]=-((2 \[Rho])/(a C[f] \[Sigma][a]-a \[Rho]^2 C[f] \[Sigma][a]));Gdown[f,a]=-((2 \[Rho])/(a C[f] \[Sigma][a]-a \[Rho]^2 C[f] \[Sigma][a]));Gdown[a,a]=-(2/((-1+\[Rho]^2) \[Sigma][a]^2));


\[CapitalGamma]udd[p_,i_,j_]:=1/2 Gup[p,f](-\!\(
\*SubscriptBox[\(\[PartialD]\), \(f\)]\(Gdown[i, j]\)\)+\!\(
\*SubscriptBox[\(\[PartialD]\), \(j\)]\(Gdown[f, i]\)\)+\!\(
\*SubscriptBox[\(\[PartialD]\), \(i\)]\(Gdown[j, f]\)\))+1/2 Gup[f,a](-\!\(
\*SubscriptBox[\(\[PartialD]\), \(a\)]\(Gdown[i, j]\)\)+\!\(
\*SubscriptBox[\(\[PartialD]\), \(j\)]\(Gdown[a, i]\)\)+\!\(
\*SubscriptBox[\(\[PartialD]\), \(i\)]\(Gdown[j, a]\)\))


Ruddd[i_,j_,k_,l_]:=-\!\(
\*SubscriptBox[\(\[PartialD]\), \(l\)]\(\[CapitalGamma]udd[i, k, j]\)\)+\!\(
\*SubscriptBox[\(\[PartialD]\), \(k\)]\(\[CapitalGamma]udd[i, l, j]\)\)+\[CapitalGamma]udd[i,k,f]\[CapitalGamma]udd[f,l,j]+\[CapitalGamma]udd[i,k,a]\[CapitalGamma]udd[a,l,j]-\[CapitalGamma]udd[i,l,f]\[CapitalGamma]udd[f,k,j]-\[CapitalGamma]udd[i,l,a]\[CapitalGamma]udd[a,k,j]


Rdd[j_,l_]:=Ruddd[f,j,f,l]+Ruddd[a,j,a,l]



