(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



LocalVolCall[CC_,CCDev1_,CCDev2_,CCInvInteg_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav},
fav=(F+K)/2;
w=1/Sqrt[2 T] (CCInvInteg[K]-CCInvInteg[F]);
H1=2(E^-w^2+Sqrt[\[Pi] w^2](NormDis[Sqrt[2]Abs[w]-1]));
H2=2/3 (E^-w^2 (1-2w^2)-2(Abs[w])^3 Sqrt[\[Pi]](NormDis[Sqrt[2]Abs[w]]-1));
Q=CC[fav]^2/4 ((CCDev2[fav]/CC[fav])-1/2 (CCDev1[fav]/CC[fav])^2);
Max[F-K,0]+Sqrt[CC[K] CC[F] T]/(2Sqrt[2\[Pi]]) (H1+T H2 Q)
]


LocalVolBSVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_]:=Module[{w,H1,H2,Q,fav,b1,b2,b3},
fav=(F+K)/2;
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
Log[K/F]/(CCInvInteg[K]-CCInvInteg[F]) (1+T (b3))
]


StochVolBSVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_,fav_]:=Module[{w,H1,H2,Q,b1,b2,b3,x,z},
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);
b2=1/4 CCDev1[fav] \[Nu] \[Rho];
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
z=(CCInvInteg[F]-CCInvInteg[K]);
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[F-K]<10^-7,Abs[CC[F]] /F (1+T (b1+b2+b3)),Abs[Log[F/K]/x] (1+T (b1+b2+b3))]
]


StochVolNormVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_,fav_]:=Module[{w,H1,H2,Q,b1,b2,b3,x,z},
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);b2=1/4 CCDev1[fav] \[Nu] \[Rho];b3=1/24  (2 CCDev2[fav]CC[fav]-(CCDev1[fav])^2+CC[fav]^2);
z=CCInvInteg[F]-CCInvInteg[K];
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[F-K]<10^-7,Abs[CC[F]] (1+T (b1+b2+b3)),Abs[(K-F)/x] (1+T (b1+b2+b3))]]


 SABRHaganBSVol[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{z,x,Effetmat},z=(f^(1-\[Beta])-K^(1-\[Beta]))/(\[Alpha] (1-\[Beta]));
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
Effetmat=(1+(1/24 \[Alpha]^2 (1-\[Beta])^2 (f K)^(-1+\[Beta])+1/4 \[Alpha] \[Beta] (f K)^(1/2 (-1+\[Beta])) \[Nu] \[Rho]+1/24 \[Nu]^2 (2-3 \[Rho]^2)) T)/(1+1/24 (1-\[Beta])^2 Log[f/K]^2+((1-\[Beta])^4 Log[f/K]^4)/1920);
If[z==0,K^(-1+\[Beta]) \[Alpha] Effetmat,
\[Alpha]/(f K)^((1-\[Beta])/2 ) z/x  Effetmat  ]]


SABRHaganCallBSOption[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=BS[F,K,T,SABRHaganBSVol[F,K,\[Alpha],T,\[Beta],\[Rho],\[Nu]]]


SABRHaganCallBSDigitale[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=SABRHaganCallBSOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K+shift,T];
s2=SABRHaganCallBSOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)
]


 SABRHaganNormVol[f_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{z,x,Effetmat,b1,b2,b3,fav},
z=(f^(1-\[Beta])-K^(1-\[Beta]))/(\[Alpha] (1-\[Beta]));fav=(f+K)/2;
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);
b2=1/4 \[Alpha] \[Beta] fav^(\[Beta]-1) \[Nu] \[Rho];
b3=1/24 fav^(-2+2 \[Beta]) \[Alpha]^2 (\[Beta]-1)^2;
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[f-K]<10^-7,Abs[\[Alpha] f^\[Beta]] (1+T (b1+b2+b3)),Abs[(K-f)/x] (1+T (b1+b2+b3))]]


SABRHaganCallNormOption[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=BS[F,K,T,SABRHaganNormVol[F,K,\[Alpha],T,\[Beta],\[Rho],\[Nu]]]


SABRHaganCallNormDigitale[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=SABRHaganCallNormOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K+shift,T];
s2=SABRHaganCallNormOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)
]


SABRCC[F_,alpha_,beta_]:=alpha F^beta


SABRCCDev1[F_,alpha_,beta_]:=alpha beta F^(beta-1)


SABRCCDev2[F_,alpha_,beta_]:=alpha  beta (beta-1) F^(beta-2)


SABRCCInvInteg[F_,alpha_,beta_]:=F^(1-beta)/((1-beta)alpha)


SABRCallBSVol[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{fav=F},
StochVolBSVol[(SABRCC[#,\[Alpha],\[Beta]])&,(SABRCCDev1[#,\[Alpha],\[Beta]])&,(SABRCCDev2[#,\[Alpha],\[Beta]])&,(SABRCCInvInteg[#,\[Alpha],\[Beta]])&,\[Rho],\[Nu],F,K,T,fav]
]


SABRCallBSOption[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=BS[K,K,T,SABRCallBSVol[F,\[Alpha],\[Beta],\[Rho],\[Nu],K,T]]


SABRCallBSDigitale[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=SABRCallBSOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K+shift,T];
s2=SABRCallBSOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)
]


SABRCallNormVol[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{fav=(F+K)/2},
StochVolNormVol[(SABRCC[#,\[Alpha],\[Beta]])&,(SABRCCDev1[#,\[Alpha],\[Beta]])&,(SABRCCDev2[#,\[Alpha],\[Beta]])&,(SABRCCInvInteg[#,\[Alpha],\[Beta]])&,\[Rho],\[Nu],F,K,T,fav]
]


SABRCallNormOption[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=NormalCall[F,SABRCallNormVol[F,\[Alpha],\[Beta],\[Rho],\[Nu],K,T],K,T]


SABRCallNormDigitale[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=SABRCallNormOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K+shift,T];
s2=SABRCallNormOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)]



ESABRCC[F_,alpha_,beta_,\[Epsilon]_]:=alpha (\[Epsilon]+F)^beta


ESABRCCDev1[F_,alpha_,beta_,\[Epsilon]_]:=alpha beta (\[Epsilon]+F)^(beta-1)


ESABRCCDev2[F_,alpha_,beta_,\[Epsilon]_]:=alpha  beta (beta-1) (\[Epsilon]+F)^(beta-2)


ESABRCCInvInteg[F_,alpha_,\[Beta]_,\[Epsilon]_]:=(F \[Epsilon]^(-\[Beta]/2) Hypergeometric2F1[1/2,\[Beta]/2,3/2,-(F^2/\[Epsilon])])/alpha


ESABRCallBSVol[F_,K_,vol_,T_,beta_,\[Rho]_,\[Nu]_,\[Epsilon]_]:=
Module[{},
StochVolBSVol[(ESABRCC[#,vol,beta,\[Epsilon]])&,(ESABRCCDev1[#,vol,beta,\[Epsilon]])&,(ESABRCCDev2[#,vol,beta,\[Epsilon]])&,(ESABRCCInvInteg[#,vol,beta,\[Epsilon]])&,\[Rho],\[Nu],F,K,T]
]


ESABRCallNormVol[F_,K_,alpha_,T_,beta_,\[Rho]_,\[Nu]_,\[Epsilon]_]:=
Module[{},
StochVolNormVol[(ESABRCC[#,alpha,beta,\[Epsilon]])&,(ESABRCCDev1[#,alpha,beta,\[Epsilon]])&,(ESABRCCDev2[#,alpha,beta,\[Epsilon]])&,(ESABRCCInvInteg[#,alpha,beta,\[Epsilon]])&,\[Rho],\[Nu],F,K,T,F]
]


EZSABRCC[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=\[Alpha] Sech[(F-F0)/\[Gamma]] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2)


EZSABRCCDev1[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=\[Alpha] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2) ((\[Beta] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]]))/(\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))-(Sech[(F-F0)/\[Gamma]] Tanh[(F-F0)/\[Gamma]])/\[Gamma])


EZSABRCCDev2[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=\[Alpha] (\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))^(\[Beta]/2) (-(Sech[(F-F0)/\[Gamma]]^3/\[Gamma]^2)+((-2+\[Beta]) \[Beta] Cosh[(F-F0)/\[Gamma]] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2)/(\[Epsilon]^2 (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon])^2)+(\[Beta] Cosh[(F-F0)/\[Gamma]])/(\[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))-(\[Beta] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]]) Tanh[(F-F0)/\[Gamma]])/(\[Gamma] \[Epsilon] (1+(F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon]))+(Sech[(F-F0)/\[Gamma]] Tanh[(F-F0)/\[Gamma]]^2)/\[Gamma]^2)


EZSABRCCInvInteg[F_,F0_,\[Alpha]_,\[Beta]_,\[Epsilon]_,\[Gamma]_]:=1/\[Alpha]  \[Epsilon]^(-\[Beta]/2) (Hypergeometric2F1[1/2,\[Beta]/2,3/2,-((F0+\[Gamma] Sinh[(F-F0)/\[Gamma]])^2/\[Epsilon])] (F0+\[Gamma] Sinh[(F-F0)/\[Gamma]]))


EZSABRCallBSVol[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_,K_,T_]:=
Module[{fav=F},
StochVolBSVol[(EZSABRCC[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev1[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev2[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCInvInteg[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,\[Rho],\[Nu],F,K,T,fav]
]


EZSABRCallBSOption[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_,K_,T_]:=BS[K,K,T,EZSABRCallBSVol[F,\[Alpha],\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma],K,T]]


EZSABRCallBSDigitale[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=EZSABRCallBSOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma],K+shift,T];
s2=EZSABRCallBSOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma],K-shift,T];
(s2-s1)/(2shift)
]


EZSABRCallNormVol[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_,K_,T_]:=
Module[{fav=F},
StochVolNormVol[(EZSABRCC[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev1[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCDev2[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,(EZSABRCCInvInteg[#,F,\[Alpha],\[Beta],\[Epsilon],\[Gamma]])&,\[Rho],\[Nu],F,K,T,fav]
]


EZSABRCallNormOption[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_,K_,T_]:=NormalCall[F,EZSABRCallNormVol[F,K,\[Alpha],T,\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma]],K,T]


EZSABRCallNormDigitale[F_,\[Alpha]_,\[Beta]_,\[Rho]_,\[Nu]_,\[Epsilon]_,\[Gamma]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=EZSABRCallNormOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma],K+shift,T];
s2=EZSABRCallNormOption[F,\[Alpha],\[Beta],\[Rho],\[Nu],\[Epsilon],\[Gamma],K-shift,T];
(s2-s1)/(2shift)]



PSABRCC[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=\[Alpha] ((1/(1+F^(\[Beta]1-\[Beta]2) (E^(\[Lambda] F)-1))) F^\[Beta]1+F^\[Beta]2 (1-1/(1+F^(\[Beta]1-\[Beta]2) (E^(\[Lambda] F)-1))))


PSABRCCDev1[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=(E^(F \[Lambda]) F^(-1+\[Beta]1+\[Beta]2) \[Alpha] (F^\[Beta]2 \[Beta]1+(-1+E^(F \[Lambda])) F^\[Beta]1 \[Beta]2-F^(1+\[Beta]1) \[Lambda]+F^(1+\[Beta]2) \[Lambda]))/((-1+E^(F \[Lambda])) F^\[Beta]1+F^\[Beta]2)^2


PSABRCCDev2[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=1/((-1+E^(F \[Lambda])) F^\[Beta]1+F^\[Beta]2)^3 E^(F \[Lambda]) F^(-2+\[Beta]1+\[Beta]2) \[Alpha] (F^(2 \[Beta]2) (-1+\[Beta]1) \[Beta]1+(-1+E^(F \[Lambda]))^2 F^(2 \[Beta]1) (-1+\[Beta]2) \[Beta]2-(-1+E^(F \[Lambda])) F^(\[Beta]1+\[Beta]2) (\[Beta]1+\[Beta]1^2+\[Beta]2-4 \[Beta]1 \[Beta]2+\[Beta]2^2)+2 F^(1+2 \[Beta]2) \[Beta]1 \[Lambda]-2 (-1+E^(F \[Lambda])) F^(1+2 \[Beta]1) \[Beta]2 \[Lambda]-2 F^(1+\[Beta]1+\[Beta]2) (\[Beta]1+E^(F \[Lambda]) \[Beta]1+\[Beta]2-2 E^(F \[Lambda]) \[Beta]2) \[Lambda]+(1+E^(F \[Lambda])) F^(2+2 \[Beta]1) \[Lambda]^2-(2+E^(F \[Lambda])) F^(2+\[Beta]1+\[Beta]2) \[Lambda]^2+F^(2+2 \[Beta]2) \[Lambda]^2)


PSABRCCInvInteg[F_,K_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_]:=1/\[Alpha] ((F^(1-\[Beta]2)-K^(1-\[Beta]2)) /(1-\[Beta]2)+\[Lambda]^(\[Beta]1-1) (-Gamma[1-\[Beta]1,F \[Lambda]]+Gamma[1-\[Beta]1,K \[Lambda]])+\[Lambda]^(\[Beta]2-1) (Gamma[1-\[Beta]2,F \[Lambda]]-Gamma[1-\[Beta]2,K \[Lambda]]))


PSABRCallBSVol[F_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{fav=F},
StochVolBSVol[(PSABRCC[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev1[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev2[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCInvInteg[F,#,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,\[Rho],\[Nu],F,K,T,fav]
]


PSABRCallBSOption[F_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_,K_,T_]:=BS[K,K,T,PSABRCallBSVol[F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu],K,T]]


PSABRCallBSDigitale[F_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=PSABRCallBSOption[F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu],K+shift,T];
s2=PSABRCallBSOption[F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)
]


PSABRCallNormVol[F_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_,K_,T_]:=
Module[{fav=F},
StochVolNormVol[(PSABRCC[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev1[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCDev2[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,(PSABRCCInvInteg[#,F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda]])&,\[Rho],\[Nu],F,K,T,fav]
]


PSABRCallNormOption[F_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_,K_,T_]:=NormalCall[F,PSABRCallNormVol[F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu],K,T],K,T]


PSABRCallNormDigitale[F_,\[Alpha]_,\[Beta]1_,\[Beta]2_,\[Lambda]_,\[Rho]_,\[Nu]_,K_,T_]:=Module[{s1,s2,shift=0.00001},
s1=PSABRCallNormOption[F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu],K+shift,T];
s2=PSABRCallNormOption[F,\[Alpha],\[Beta]1,\[Beta]2,\[Lambda],\[Rho],\[Nu],K-shift,T];
(s2-s1)/(2shift)]



StochVolBSVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_,fav_]:=Module[{w,H1,H2,Q,b1,b2,b3,x,z},
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);
b2=1/4 CCDev1[fav] \[Nu] \[Rho];
b3=(CC[fav])^2/24 ((2CCDev2[fav])/CC[fav]-(CCDev1[fav]/CC[fav])^2+1/fav^2);
z=(CCInvInteg[F]-CCInvInteg[K]);
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[F-K]<10^-7,Abs[CC[F]] /F (1+T (b1+b2+b3)),Abs[Log[F/K]/x] (1+T (b1+b2+b3))]
]


StochVolNormVol[CC_,CCDev1_,CCDev2_,CCInvInteg_,\[Rho]_,\[Nu]_,F_,K_,T_,fav_]:=Module[{w,H1,H2,Q,b1,b2,b3,x,z},
b1=1/24 \[Nu]^2 (2-3 \[Rho]^2);b2=1/4 CCDev1[fav] \[Nu] \[Rho];b3=1/24  (2 CCDev2[fav]CC[fav]-(CCDev1[fav])^2+CC[fav]^2);
z=CCInvInteg[F]-CCInvInteg[K];
x=Log[(-\[Rho]+\[Nu] z+Sqrt[1-2 \[Nu] \[Rho] z+\[Nu]^2 z^2])/(1-\[Rho])]/\[Nu];
If[Abs[F-K]<10^-7,Abs[CC[F]] (1+T (b1+b2+b3)),Abs[(K-F)/x] (1+T (b1+b2+b3))]]



